Repository feelpp/benchmarking, pull requests merged in 2024-10, with the labels that each got.

#59 improve feelpp benchmarking packaging
  .README.adoc
  docs/modules/gaya/images/gaya-back.jpeg
  docs/modules/gaya/images/gaya-front.jpeg
  docs/modules/gaya/images/gaya.jpg
  docs/modules/gaya/images/gaya.png
  requirements.txt
Labels: enhancement

#85 78 refactor report figures
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar2d/gaya/2024-10-04T10:36:30+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar3d/gaya/2024-10-04T10:36:52+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_1/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_1/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_2/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_2/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_3/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_3/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_4/gaya/2024-10-04T10:36:30+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_4/gaya/2024-10-04T10:36:52+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_4/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_4/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heatfluid/laminar2d/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heatfluid/laminar2d/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heatfluid/laminar3d/gaya/2024-10-04T10:36:30+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heatfluid/laminar3d/gaya/2024-10-04T10:36:52+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heatfluid/laminar3d/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heatfluid/laminar3d/index.adoc
  src/feelpp/benchmarking/feelpp_toolboxes/reframe/report.py
  src/feelpp/benchmarking/report/components/atomicReport.py
  src/feelpp/benchmarking/report/components/controllers/__init__.py
  src/feelpp/benchmarking/report/components/controllers/atomicReportController.py
  src/feelpp/benchmarking/report/components/models/__init__.py
  src/feelpp/benchmarking/report/components/models/atomicReportModel.py
  src/feelpp/benchmarking/report/components/strategies.py
  src/feelpp/benchmarking/report/components/views/__init__.py
  src/feelpp/benchmarking/report/components/views/atomicReportView.py
  src/feelpp/benchmarking/report/config.json
  src/feelpp/benchmarking/report/templates/benchmark.adoc.j2
Labels: enhancement, code-quality

#87 72 refactor document and modularise code
  .gitignore
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar2d/gaya/2024-10-04T14:04:58+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar3d/gaya/2024-10-04T10:36:52+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar3d/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar3d/index.adoc
  pyproject.toml
  reports/feelpp_toolbox_electric/gaya/20241004T103630-busbar2d.json
  reports/feelpp_toolbox_electric/gaya/20241004T103652-busbar3d.json
  reports/feelpp_toolbox_electric/gaya/2024_10_04T14_04_57.json
  reports/feelpp_toolbox_heat/gaya/20241004T103630-busbar2d.json
  reports/feelpp_toolbox_heat/gaya/20241004T103652-busbar3d.json
  reports/feelpp_toolbox_heatfluid/gaya/20241004T103630-busbar2d.json
  reports/feelpp_toolbox_heatfluid/gaya/20241004T103652-busbar3d.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigTemplate.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/electric/busbar2d.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/electric/busbar3d.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heat/ThermalBridgesCase2.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heat/ThermalBridgesCase3.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heat/ThermalBridgesCase4.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heatfluid/2dLaminar.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heatfluid/3dLaminar.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heatfluid/proneEye-M2-lsc.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heatfluid/proneEye-M2-simple.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heatfluid/proneEye-M3-lsc.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/benchConfigs/heatfluid/proneEye-M3-simple.json
  src/feelpp/benchmarking/feelpp_toolboxes/config/configReader.py
  src/feelpp/benchmarking/feelpp_toolboxes/config/configSchema.json
  src/feelpp/benchmarking/feelpp_toolboxes/launchProcess.py
  src/feelpp/benchmarking/feelpp_toolboxes/parser.py
  src/feelpp/benchmarking/feelpp_toolboxes/reframe/regression-tests/__init__.py
  src/feelpp/benchmarking/feelpp_toolboxes/reframe/regression-tests/cpuVariation.py
  src/feelpp/benchmarking/feelpp_toolboxes/reframe/regression-tests/setup.py
  src/feelpp/benchmarking/reframe/__init__.py
  src/feelpp/benchmarking/reframe/__main__.py
  src/feelpp/benchmarking/reframe/config/__init__.py
  src/feelpp/benchmarking/reframe/config/benchmarkConfigTemplate.json
  src/feelpp/benchmarking/reframe/config/configReader.py
  src/feelpp/benchmarking/reframe/config/configSchemas.py
  src/feelpp/benchmarking/reframe/config/executionConfigTemplate.json
  src/feelpp/benchmarking/reframe/config/gayaExec.json
  src/feelpp/benchmarking/reframe/config/machineConfigs/__init__.py
  src/feelpp/benchmarking/reframe/config/machineConfigs/gaya.py
  src/feelpp/benchmarking/reframe/config/machineConfigs/local.py
  src/feelpp/benchmarking/reframe/parameters.py
  src/feelpp/benchmarking/reframe/parser.py
  src/feelpp/benchmarking/reframe/regression.py
  src/feelpp/benchmarking/reframe/scalability.py
  src/feelpp/benchmarking/reframe/setup.py
  src/feelpp/benchmarking/reframe/validation.py
  src/feelpp/benchmarking/report/components/atomicReport.py
  src/feelpp/benchmarking/report/components/repositories.py
  src/feelpp/benchmarking/report/components/strategies.py
  src/feelpp/benchmarking/report/config.json
  src/feelpp/benchmarking/report/templates/benchmark.adoc.j2
Labels: enhancement, cleanup, code-quality

#92 89 parametrize figure generation
  .github/workflows/ci.yml
  .github/workflows/regression.yml
  config/electric.json
  config/gaya.json
  config/heat.json
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar2d/gaya/2024-10-07T14:21:51+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar2d/gaya/2024-10-07T14:35:34+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/busbar2d/gaya/2024-10-09T14:26:39+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/quarter_turn_3d/gaya/2024-10-10T15:39:18+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/quarter_turn_3d/gaya/2024-10-10T15:46:29+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/quarter_turn_3d/gaya/2024-10-10T15:59:25+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/quarter_turn_3d/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_electric/quarter_turn_3d/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_2/gaya/2024-10-09T15:37:13+0200.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_2/gaya/index.adoc
  docs/modules/ROOT/pages/applications/feelpp_toolbox_heat/thermal_bridges_case_2/index.adoc
  netlify-build.sh
  pyproject.toml
  reports/feelpp_toolbox_electric/gaya/2024_10_09T14_26_38/plots.json
  reports/feelpp_toolbox_electric/gaya/2024_10_09T14_26_38/reframe_report.json
  reports/feelpp_toolbox_electric/gaya/2024_10_10T15_39_17/plots.json
  reports/feelpp_toolbox_electric/gaya/2024_10_10T15_39_17/reframe_report.json
  reports/feelpp_toolbox_electric/gaya/2024_10_10T15_46_29/plots.json
  reports/feelpp_toolbox_electric/gaya/2024_10_10T15_46_29/reframe_report.json
  reports/feelpp_toolbox_electric/gaya/2024_10_10T15_59_25/plots.json
  reports/feelpp_toolbox_electric/gaya/2024_10_10T15_59_25/reframe_report.json
  reports/feelpp_toolbox_heat/gaya/2024_10_09T15_37_13/plots.json
  reports/feelpp_toolbox_heat/gaya/2024_10_09T15_37_13/reframe_report.json
  requirements.txt
  src/feelpp/benchmarking/reframe/__main__.py
  src/feelpp/benchmarking/reframe/config/configSchemas.py
  src/feelpp/benchmarking/reframe/parameters.py
  src/feelpp/benchmarking/reframe/scalability.py
  src/feelpp/benchmarking/report/components/atomicReport.py
  src/feelpp/benchmarking/report/components/controllers/__init__.py
  src/feelpp/benchmarking/report/components/controllers/atomicReportController.py
  src/feelpp/benchmarking/report/components/figureFactory.py
  src/feelpp/benchmarking/report/components/models/__init__.py
  src/feelpp/benchmarking/report/components/models/atomicReportModel.py
  src/feelpp/benchmarking/report/components/repositories.py
  src/feelpp/benchmarking/report/components/strategies.py
  src/feelpp/benchmarking/report/components/views/__init__.py
  src/feelpp/benchmarking/report/components/views/atomicReportView.py
  src/feelpp/benchmarking/report/config.json
  src/feelpp/benchmarking/report/handlers.py
  src/feelpp/benchmarking/report/templates/benchmark.adoc.j2
Labels: enhancement
