Repository feelpp/benchmarking, pull requests merged in 2025-03, with the labels that each got.

#261 257 write script to init antora prerequisites
  README.adoc
  README.md
  config/toolbox_heat/heat_plots.json
  docs/modules/tutorial/pages/configurationfiles/machine.adoc
  docs/modules/tutorial/pages/gettingstarted.adoc
  pyproject.toml
  src/feelpp/benchmarking/reframe/config/configReader.py
  src/feelpp/benchmarking/reframe/config/machineConfigs/meluxina/reframe.py
  src/feelpp/benchmarking/reframe/config/machineConfigs/vega/reframe.py
  src/feelpp/benchmarking/reframe/regression.py
  src/feelpp/benchmarking/reframe/resources.py
  src/feelpp/benchmarking/reframe/setup.py
  src/feelpp/benchmarking/report/__main__.py
  src/feelpp/benchmarking/report/atomicReports/atomicReport.py
  src/feelpp/benchmarking/report/atomicReports/repository.py
  src/feelpp/benchmarking/report/figures/base.py
  src/feelpp/benchmarking/report/figures/plotlyFigures.py
  src/feelpp/benchmarking/report/parser.py
  src/feelpp/benchmarking/scripts/antora.py
  src/feelpp/benchmarking/scripts/data/antora.yml.j2
  src/feelpp/benchmarking/scripts/data/package.json
  src/feelpp/benchmarking/scripts/data/site.yml.j2
Labels: bug: fte, enhancement

#275 resolves : 272-support-ctrc-reframe
  src/feelpp/benchmarking/reframe/__main__.py
Labels: enhancement

#284 Add BSD-3 license
  LICENSE
Labels: enhancement

#280 Add GitHub Actions workflow for creating releases
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: ci-cd

#273 Support meluxina and karolina
  .github/workflows/benchmark.yml
  .github/workflows/benchmark_deploy.yml
  src/feelpp/benchmarking/reframe/config/machineConfigs/karolina/setup.sh
  src/feelpp/benchmarking/reframe/config/machineConfigs/meluxina/launchBenchmark.sh
Labels: enhancement, hpc

#288 resolves 286: use antora like reference when manipulating file in antora filesystem
  .github/workflows/ci.yml
  docs/modules/tutorial/attachments/data/plots.json
  docs/modules/tutorial/attachments/data/reframe_report.json
  docs/modules/tutorial/pages/configurationfiles/plots.adoc
  netlify-build.sh
  package-lock.json
  package.json
Labels: bug

#285 268 add training material
  docs/antora.yml
  docs/modules/training/images/aggregation_example.png
  docs/modules/training/images/bench_supercomputers.png
  docs/modules/training/images/benchmark_code_design.png
  docs/modules/training/images/benchmark_workflow.jpg
  docs/modules/training/images/dashboard_workflow.jpg
  docs/modules/training/images/fibonacci_time_complexity_plot.png
  docs/modules/training/images/logoCemosis.png
  docs/modules/training/images/plot_example.png
  docs/modules/training/images/reframe-logo-dark-bg.png
  docs/modules/training/images/reframe-system-arch.svg
  docs/modules/training/images/reframe-test-cases.svg
  docs/modules/training/images/reframe_logo-width400p.png
  docs/modules/training/nav.adoc
  docs/modules/training/pages/advanced/containers.adoc
  docs/modules/training/pages/advanced/custom_perfvars.adoc
  docs/modules/training/pages/advanced/file_dependencies.adoc
  docs/modules/training/pages/advanced/handsOn/index.adoc
  docs/modules/training/pages/advanced/index.adoc
  docs/modules/training/pages/advanced/memory.adoc
  docs/modules/training/pages/advanced/remote_files.adoc
  docs/modules/training/pages/advanced/visualization.adoc
  docs/modules/training/pages/advanced/workflow.adoc
  docs/modules/training/pages/index.adoc
  docs/modules/training/pages/reframe/benchmark_specs.adoc
  docs/modules/training/pages/reframe/conclusion.adoc
  docs/modules/training/pages/reframe/example_app.adoc
  docs/modules/training/pages/reframe/executing.adoc
  docs/modules/training/pages/reframe/handsOn/exercise1.adoc
  docs/modules/training/pages/reframe/handsOn/exercise2.adoc
  docs/modules/training/pages/reframe/handsOn/index.adoc
  docs/modules/training/pages/reframe/index.adoc
  docs/modules/training/pages/reframe/introduction.adoc
  docs/modules/training/pages/reframe/machine_specs.adoc
  docs/modules/training/pages/reframe/plot_specs.adoc
  docs/modules/training/pages/reframe/settings.adoc
  examples/fibonacci/benchmark.json
  examples/fibonacci/fibonacci.py
  examples/fibonacci/plots.json
  examples/matrixvector/matrixvector
  examples/matrixvector/matrixvector.cpp
  examples/matrixvector/matrixvector.json
  examples/matrixvector/plots.json
Labels: documentation

#291 Add training handson 2
  docs/modules/training/images/mesh_stats.png
  docs/modules/training/images/thermalBridgesMaterials.png
  docs/modules/training/images/thermalBridgesPartitioning.png
  docs/modules/training/pages/advanced/handsOn/exercice1.adoc
  docs/modules/training/pages/advanced/handsOn/index.adoc
  docs/modules/training/pages/reframe/handsOn/exercise2.adoc
Labels: documentation
